"""empty message

Revision ID: cc24983ece83
Revises: a3c55471532c
Create Date: 2022-01-31 14:36:19.969967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc24983ece83'
down_revision = 'a3c55471532c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'location')
    op.drop_column('user', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
